name: Create new ADR

on:
  workflow_dispatch:
    inputs:
      title:
        description: 'タイトル'
        required: false
        type: string
        

jobs:
  create-pr:
    runs-on: ubuntu-20.04
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.91.2'
          # extended: true

      - name: Create new file and pull request
        run: |
          pr_name=`date '+%Y%m%d-%H'`
          set -x
          git checkout -b ${pr_name}
          hugo new "adr/${pr_name}-${{ github.event.inputs.title }}.md"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m 'Create new adr'
          git push origin ${pr_name}
          gh pr create -B main -t "${{ github.event.inputs.title }}" -b ""
